### ISSUE TITLE
TODO: Add complete support for Grantha

### ISSUE THREAD

**Issue by akprasad** [ambuda-org/vidyut#90]
This is a tracking issue for ongoing work related to Grantha, such as issue #85. +cc @deepestblue as a resident Grantha expert.

Documentation:
- http://www.unicode.org/charts/PDF/U11300.pdf
- https://unicode.org/L2/L2009/09372-grantha.pdf

Relevant prior work:
- [SaulabhyaJS](https://github.com/deepestblue/saulabhyaJS/tree/main)
- Perhaps [Aksharamukha](https://github.com/virtualvinodh/aksharamukha-python) as well

Scope of work:
- `vidyut-lipi` should be able to transliterate all Grantha features (as defined in U11300) to at least one other script. For Sanskrit sounds, this can be Devanagari. For Dravidian sounds, this can be Tamil, etc.
- `vidyut-lipi` should support transliterating to and from Grantha numerals (see #85). I think this should be a transliteration option that is on by default. That is, `vidyut-lipi` should be updated to support transliteration options.

Known work remaining:
- [x] Grantha svara markers for the Samaveda
- [x] Grantha pluta and double anusvara
- [x] Grantha sign anusvara (U+11302)

Validation:
- All Grantha features must be captured in at least one automatic test. Currently, all of our transliteration tests are in `basic.rs`.
- Sign-off by an expert in Grantha usage.

**Comment by deepestblue** [comment]
* 𑍞 maps to ꣳ
* 𑍟 maps to ꣴ
* The Nuqta was introduced into Devanagari to write Perso-Arabic characters, and there's no documented usage of it in Grantha. That said, the GoI wanted to encode it as an extension point, and so I guess U+1133C maps to U+093C
* 𑍝 is a challenge; it's a pluti-marker, which in Devanagari is simply indicated by the digit 3 (U+0969), and roundtripping here is going to be hard
* [U+1133B I believe is used for Nilagiri tribal languages and not for Sanskrit](https://www.unicode.org/L2/L2016/16084-badaga-single-dot.pdf). Arguably it doesn't belong in Grantha, [a point which Vid. Shriramana made unsuccessfully with the Unicode folks.](https://www.unicode.org/L2/L2016/16115-tamil-nukta-reiteration.txt) I'd leave it out of vidyut.
* [U+11300 is used for Prakrita languages and again not in Sanskrit](https://www.unicode.org/L2/L2013/13061-grantha-anusvara-above.pdf). We should ignore it in vidyut unless you want to support Prakrit.
* I'll defer to Vid. Shriramana on Samaveda marks, on which my knowledge is very limited :-(

**Comment by deepestblue** [comment]
> If this lossily maps to Devanagari 3, policies in the reverse direction might be:

I think map back to the pluti-marker after a vowel makes the most sense.

> > U+11300 is used for Prakrita languages [...] We should ignore it in vidyut unless you want to support Prakrit.

> I would like to support it if possible. Does this map to U+0902 Devanagari sign anusvara?

Yes, but in the Prakrita cases where it maps to U+0902, U+11302 should *not* map to U+0902, but instead indicates doubling (gemination) of the subsequent consonant, for which Devanagari doesn't have a symbol. So the next effect is pretty lossy. You may already know this, as the PDF I linked to has this detail.

**Comment by deepestblue** [comment]
> the DOUBLE ANUSVARA (don't know how to handle)

Do you mean U+1135F 𑍟? If so, I mentioned above that it maps to U+A8F4 ꣴ.

**Comment by deepestblue** [comment]
I believe the pluti marker comes after long vowels, not short. In Grantha, they should be 

"𑌆𑍝 𑌈𑍝 𑌊𑍝 𑍠𑍝 𑌏𑍝 𑌐𑍝 𑌓𑍝 𑌔𑍝" and "𑌕𑌾𑍝 𑌕𑍀𑍝 𑌕𑍂𑍝 𑌕𑍄𑍝 𑌕𑍇𑍝 𑌕𑍈𑍝 𑌕𑍋𑍝 𑌕𑍌𑍝"

although not all of these may be attested in practice.

I don't know H-K enough to be able to help there. The Devanagari should be straightforward enough, although lossy as it reuses the symbol for 3.

**Comment by vvasuki** [comment]
द्वेधापि दृश्यन्ते, दीर्घात् परम् एव प्रचुरम् -

> अग्ना३ इ पत्नी॒वा३स्स॒जूर्दे॒वेन॒ त्वष्ट्रा॒ सोम॑म्पिब॒ स्वाहा᳚ ॥

> "उप॒स्थेयो॒ ऽग्नी३र् नोप॒स्थेया३"

> सोऽ३॒॑ पोऽ३॒॑भ्य॑म्रियत ।

> सुश्लोक ३ सुमंगलाँ३ सत्य॑राजा३न्,

> सु॒श्लो॒काँ३सुम॑ङ्गुल३ सत्य॑रा॒जा३न, इति ।

**Comment by vvasuki** [comment]
cc @jamadagni @virtualvinodh

**Comment by deepestblue** [comment]
LGTM

**Comment by jamadagni** [comment]
> अनुगृहीतोऽस्मि। OK, here's my mental model based on the comments and examples above:
> 
>     * pluta (`3`) can follow any vowel
> 
>     * the vowel can be independent (इ) or a mark (कि) or the inherent vowel of a consonant (क).
> 
>     * the vowel can be either short (इ) or long (ई) and varies by custom.
> 
>     * the vowel may optionally be followed by a candrabindu.
> 
>     * `3` may optionally receive svaras.

सम्यग् इति भाति। यद्यपि प्लुतस्य स्वरचिह्नसम्बन्धः अतीव दुर्लभः तथाऽपि क्वचिद् व्याकरणानुसारेण भवति।
